### ISSUE TITLE
Errors under Windows with rc1

### ISSUE THREAD

**Issue by sebastianrueckerai** [HungryProton/scatter#103]
Hi!

I am trying to convert my 3.5 project to 4.0 (rc1).

After adding scatter to the project I am getting a long list of errors:
![image](https://user-images.githubusercontent.com/83586913/218791016-b1b3b91b-f110-408c-a777-7a8677985638.png)

Any help would be appreciated!

**Comment by HungryProton** [comment]
Rename the addon folder to `proton_scatter`, that's the new name to help differentiate it with the 3 or 4 other scatter addons I've seen.

A lot have changed between 3 and 4, and you will likely have to redo all of your scatter nodes, there's currently no way around that, sorry.

The major difference is with the shape, instead of forcing everything to be a Path3D, there's a new `ScatterShape` node you have to put under the scatter root, and then pick which type of shape you want it to be (path, box or sphere for now). This allows you to use multiple shapes at once to create complex patterns, and simplifies the modifier list as well.

Check the showcase scene for examples once you get the add-on running without errors.

**Comment by sebastianrueckerai** [comment]
Awesome, thanks for the quick help! :)
