### ISSUE TITLE
Does not work in 4.1 dev3

### ISSUE THREAD

**Issue by Eisenspalter** [HungryProton/scatter#114]
Error- Message: 
```Adding children to a node inside the SceneTree is only allowed from the main thread. Use call_deferred("add_child",node).```

**Comment by HungryProton** [comment]
Thanks for the report. I'm working on it, but it's probably the most annoying bug I've had to debug so far.

**Comment by HungryProton** [comment]
Fixed* in b2f7c5b868822b0645b47c6b04bdde1a6aa40867

It **WILL NOT** work with the current beta though, because the fix relies on a function that was added to master 4 days ago. Either compile Godot from the master branch, or wait for the next beta (which shouldn't take long given how fast they release them)
