### ISSUE TITLE
ScatterItem broken in v4.0.3.stable.mono.official [5222a99f5]

### ISSUE THREAD

**Issue by Scuas** [HungryProton/scatter#115]
Adding ProtonScatter to a blank project results in the following error:
![image](https://github.com/HungryProton/scatter/assets/66699973/48f34679-8152-41ba-aeaf-0d4a51d85fd0)
When adding nodes, ProtonScatter and ScatterShape appear in the node list, but ScatterItem is missing which breaks the addon.
![image](https://github.com/HungryProton/scatter/assets/66699973/fd6dbdd8-f4c2-41fc-9a6e-6a738ba44c99)

**Comment by HungryProton** [comment]
There's a conflict with another add-on here (goshapes) that also uses a class called ScatterItem. I wish some sort of namespacing existed in Godot because I can't really work around this issue, except maybe by prefixing every class with the add-on name (which would break compatibility with existing projects).

**Comment by Scuas** [comment]
That's strange. I did try goshapes but it was disabled and deleted from this project quite a long time ago. I'm not sure why/how godot remembers this. Is there something about how godot handles addons that would be creating this conflict with goshapes' ghost?

That makes sense why ScatterItem is missing on my end though. 


Edit: Regenerating the .godot folder removed the conflict, thanks for the quick response!
