### ISSUE TITLE
How does LOD work with this plugin?

### ISSUE THREAD

**Issue by SlashScreen** [HungryProton/scatter#144]
If I have a large world with many trees, rocks, etc. Are generated LODs automatically applied to trees as the camera moves around? YOu can't do that with multi mesh instances, right? Should I instead create some kind of tool that will hide and show proton scatter clusters based on distance to the camera?

**Comment by Norodix** [comment]
You have many options.

Chunks created with instancing respect the visibility range that you set up in the scatteritem. That way you can hide far away patches of grass, rocks etc.

Scatter nodes have an enabled property that you can manually toggle from a script. You can base it on anything you want, player distance, map region etc. This frees up the generated multimesh instances and everything else, so it saves on memory. When you enable it again, it computes the scatter again, which can cause frame drop and jitter while it generates.

For trees we found that creating 1000 duplicates of a tree is much more performant. We can set up impostors, autolod or manual HLOD for the tree node. 1000 draw calls that are saved by using instancing is nothing compared to being able to cull just 1 more tree or being able to apply a lower lod to many trees. I think this applies to meshes that are big on their own. For grass and the like which is just a few polygons, 100k draw calls would not be feasible, so use multimeshes there.

**Comment by HungryProton** [comment]
The MultiMesh node has support for automatic LOD, but the add-on doesn't use this feature yet.
 
Regarding instancing, scatter duplicates the source mesh for technical reasons (that's something we could change, but it's not trivial). This means you lose the automatic LOD generated for that mesh on import, and you only get the most detailed version.

Apparently we can regenerate LODs at run time with the `ImporterMesh` class, but I haven't tried it yet. It won't have the same parameters as the importer tab, though, but we could probably expose similar settings in the ScatterItem node.

**Comment by HungryProton** [comment]
My last comment should be addressed in 6d3f66ca5cc9f7acc93e29f126702e2b4fb4ef4d

There's automatic LOD generation with instancing now, it's using the same defaults as the importer tab and is enabled by default. This can be changed on the `ScatterItem` node, under the `Level of Detail` group.

**Comment by SlashScreen** [comment]
Other question:
1. Does Keep Static Colliders work on instances?
2. What does "use chunks" mean in this context?
3. At what point should I stop using instancing and start using copies to allow for LOD and occluding? Like, for example, I have rocks and tombstones that don't have as many polygons as a tree but more than a grass clump.

**Comment by Norodix** [comment]
2. Use chunks is an option in the performance tab of scatters. It means that instead of creating a large multimesh with all the scattered objects in it, multiple smaller multimeshes are created in a grid pattern: chunks. A multimesh instance is either culled or not, there is no in-between. Assume you have 100k props scattered on the ground. That would be 100k nodes, 100k draw calls etc. Impossible for the poor PC to handle. But if you add them to a multimesh you can handle it. But if any 1 of the 100k objects are visible all must be rendered, which is quite wasteful. With chunks you can balance this. Divide the mmi into 20 parts. 20 draw calls, 20 nodes is nothing. But if you only see 1 prop, you dont have to render the other 19 chunks, 1/20th of effort. You need to test and optimize as with all other settings.
3. Test it and see which method is more performant.

**Comment by HungryProton** [comment]
1. `Keep Static Colliders` is made specifically for instancing (and particles). When creating full copies, the whole scene is instantiated (which includes scripts, colliders and everything), but with instancing, we can only use the Mesh data for that, everything else is ignored. This option allows scatter to detect the colliders, and adds them to the Physics sever directly without creating new nodes (which would be too slow)
