### ISSUE TITLE
Force rebuild on load and runtime behaviors

### ISSUE THREAD

**Issue by SlashScreen** [HungryProton/scatter#149]
What does force rebuild on load actually *do*? Whenever I open my scene in the editor it takes an age to recalculate (I am placing many trees) despite force rebuild being set to false. When I enter the game, the trees take a second to pop in - are they being recalculated? The only difference I see is that I have a number of gravestones set to instance mode that do not appear at all in-game unless force rebuild is on. The behavior of this is unclear.

**Comment by HungryProton** [comment]
Force rebuild on load does just that: forcing the scatter nodes to regenerate their nodes (either Multimesh or full copies, depending on the render mode).

With the default settings, the scatter nodes do **not** store the final result in your scenes, because that adds a lot of weight to the scene files. So when launching a game, at first you see nothing, then the scatter nodes are forced to rebuild, and you get to see something.

If you disable this option, you have two options:
+ Enable `Show output in tree` to store the results in the scene (not recommended for large amount of objects).
+ Use a `ScatterCache` node which will store the final results and apply them again at runtime.

To use a cache, simply create a ScatterCache node in your scene, it will assign it a random cache file, you can change it or leave the default path. Then you click on the `Rebuild cache` button, (or just save the scene, that should be automatic).

Scatter nodes in the scene that **don't** have force rebuild enabled will use the cache instead.

**Comment by HungryProton** [comment]
You may be using an older version of the add-on though, long build times when opening a scene (even with the option disabled) is a bug that was fixed two weeks ago I think.

**Comment by SlashScreen** [comment]
Is this fix uploaded on the assetlib?

**Comment by HungryProton** [comment]
The current asset lib version should have this fix.
