### ISSUE TITLE
Recalculating a small area?

### ISSUE THREAD

**Issue by HoutarouOreki** [HungryProton/scatter#153]
I'm using this to scatter grass, but when I place an object I don't want grass to be there anymore. Is there a better/faster way than rebuilding it all by calling .rebuild()?

https://github.com/HungryProton/scatter/assets/16261733/f3807d05-28d5-470c-9de9-bbbe40c3be5e

**Comment by HungryProton** [comment]
Not really, the add-on was not designed for real time edition. You could manually operate on the underlying Multimesh3D node and delete the instances you don't need, but that's probably going to be just as slow and needlessly complicated.

Another option would be to keep the modifier stack as simple as possible to speed up the generation process.

**Comment by HungryProton** [comment]
A more complicated solution if you're familiar enough with shaders: 

Make a custom spatial shader for the grass, that samples a black and white texture that represents where you placed your objects. (for this example, let's say, black pixels are occupied and white pixels are free space).

In the vertex function of the spatial shader, find the mesh origin in world coordinates, use that to sample the texture above, if the pixel is black, discard the whole instance, otherwise draw it as usual.

To actually generate the texture though, you have a few options, the easiest one would be to use the Image class which has some functions to draw. (Or you can use a viewport and pass the viewport texture to the shader).

That's a lot more involved though, but performance wise, that's probably the best option.
