### ISSUE TITLE
Scatter regenerates Arraymesh for every single chunk

### ISSUE THREAD

**Issue by WrobotGames** [HungryProton/scatter#158]
When using ProtonScatter with chunks enabled and when using a scene under the ScatterItem node, an Arraymesh will be generated (and saved!) for every single chunk. This results in EXTREMELY large scene files. 

For example, I'm creating a jungle scene that is 1 by 1 km and uses chunks of 100 by 100 meters. I have about 20 different types of high res trees (30 000 in total) and I enabled "show output in tree", since the scene is fairly complex. The scene file became 2 Gigabytes! Its not possible to play this scene anymore due to this size. ![afbeelding](https://github.com/HungryProton/scatter/assets/66079814/60c78644-dab1-42bb-966e-c250228b32d8)

### Recreating this issue:
setup a scene with scatter and show output to tree. Make sure that several chunks are generated, and the input mesh is a scene file.
1. Look at the scene file size difference between chunks enabled and disabled.
2. Open the scene file in a text editor and observe how the arraymesh subresource is saved for every single chunk. 
3. or, look at the resource path under the mesh of the multimesh nodes.

For the clearest results, use a hi poly mesh or a lot of chunks.

**Comment by HungryProton** [comment]
The duplicated mesh issue will be fixed in once #156 is merged.

I should really move that `Show output in tree` option away from the general tab, this was just a debug option I left there to make troubleshooting easier.

If you don't want to regenerate the whole scene, use a ScatterCache node. (And disable `Force rebuild on load` on the scatter nodes that should use the cache.

**Comment by WrobotGames** [comment]
I have tried using the ScatterCache, but the loading time gets really low for bigger scenes. That is why I use 'show output in tree'

For example, default scatter setup with 'brick.tscn', 10000 items, chunks disabled, force rebuild disabled:
- 128 by 128 scattershape, with scattercache: ~1 second loading time
- 128 by 128 scattershape, with "show output in tree": ~1 second loading time
- 1024 by 1024 scattershape, with scattercache: ~63 second loading time
- 1024 by 1024 scattershape, with "show output in tree": ~1 second loading time

Recreating the setup from my jungle scene with just "bricks" results in a loading time of more than 5 minutes with scattercache and 5 seconds with "show output in tree". The scene with scattercache was 2 MB (cache included), the other one was 43 MB.

5 minutes with a completely frozen game is not really a nice experience...

**Comment by HungryProton** [comment]
Sorry for the delay.
The bug causing a duplicate mesh per chunk has been fixed, and generally, meshes are no longer duplicated unless required by the material setup. Cache operations were also sped up in the latest commit (455accadc2cd8a76ac2a7f0e6dc58ae50ec182f1).

(Also, if you were using a cache, please change the cache file extension. It was defaulting to a text resource instead of a binary one. That was for debug purposes and I forgot to revert it. New caches won't have this issue).

**Comment by WrobotGames** [comment]
Thanks, 
The wait wasn't a problem for me. I used the draft-pr #156 and it worked really well. (It was used for basically all foliage in my jungle demo. Maybe you have seen it.)
