### ISSUE TITLE
Each time i save a scene, the sub_resource changes.

### ISSUE THREAD

**Issue by YiDoSeon** [HungryProton/scatter#212]
In my case, every time I save a scene that uses scatters, they appear as changes in git.

1. add the Scatters to the Scene, save, commit to git, and close the Scene.
2. Open that Scene again and save again without making any changes.
3. git changes shows the changes related to modifier_scatter.

I've seen the same thing both with and without ScatterCache.

Is this a godot issue? If not, how can I keep the sub_resource if I haven't made any changes?

![image](https://github.com/user-attachments/assets/ec7efa75-6fdf-4c90-9804-843dd5966dac)
![image](https://github.com/user-attachments/assets/9b644f89-7dcc-43f0-9b32-8361b9707de2)

**Comment by Mister-Ky** [comment]
there is a way to simply not call the get_copy() function in the modifier_stack property in its setter, but in this case crashes and freezes will sometimes occur

![image](https://github.com/user-attachments/assets/319acd47-d862-4a12-bd56-81b3a88498b2)

now I'm figuring out how to fix such renaming anyway, because such things are not the best for git

**Comment by HungryProton** [comment]
Latest commit 8e4738e36c10673ac83fa123eeef31d0d4176308 should fix this issue.
Git might detect one last change in the sub-resource because I had to make a change there, but after that it should only duplicate the modifier stack when the scatter node itself is duplicated.

Feel free to reopen if you still encounter this issue!
